name: Bark Notification

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Bark Notification
        run: |
          curl -L "${{ secrets.BARK_URL }}/test"
